### ISSUE TITLE
Concurrent states execute on_exit() twice

### ISSUE THREAD

**Issue by bkvaluemeal** [team-vigir/flexbe_behavior_engine#17]
![on_exit](https://cloud.githubusercontent.com/assets/3835053/16598603/cd68fcf8-42cc-11e6-8154-9cb2b718fb5c.png)
[files.tar.gz](https://github.com/team-vigir/flexbe_behavior_engine/files/348579/files.tar.gz)

**Comment by bkvaluemeal** [comment]
The files I included are a modified log state changed from working on "on_enter()" to "on_exit()" and a behavior with a single concurrent container containing 3 of those modified states. When I run the behavior, each of the 3 log messages is printed out twice as shown in the screenshot. I don't believe that is the intended behavior.

**Comment by pschillinger** [comment]
Thanks for reporting! I will look into that.

**Comment by pschillinger** [comment]
The problem was that on_exit was called once for each particular state when it finished execution and once for all states of the container when it was left. If you would connect the outcomes of the three log states to different outcomes of the container, you would have seen that only one of them is executed twice.

Should be fixed now, on_exit is only called for states when leaving the container if they are still active.
