### ISSUE TITLE
FlexBE does not connect

### ISSUE THREAD

**Issue by trgtylcnky** [team-vigir/flexbe_behavior_engine#28]
Hi, I am following the FlexBE tutorials. The problem is I never get the FlexBE app connection. Onboard Status is "disconnected". rosbridge, rosapi, flexbe_onboard are all running. Moreover, I see the message on rosbridge output "Client connected. 1 clients total." FlexBE console does not show any error. And "Connect" button on the Configuration screen is deactivated as if it is already connected. It seems some part of the program believes it is connected but others disagree.
![flexbe_does_not_connect](https://cloud.githubusercontent.com/assets/23400050/20590838/2a42043a-b22e-11e6-9ce1-c23573ae7c66.png)

**Comment by pschillinger** [comment]
Speaking from the terminal screenshot, it looks like rosbridge did not
connect to the ROS master in this case.

If rosbridge connected properly to the master, the terminal should print a
list of topics to which the FlexBE App subscribes, including the topic
"/flexbe/heartbeat". If this subscription is successful and there are
messages published on this topic, then the status should change to "online".

Btw: If you disconnect the App from rosbridge, it will say "offline"
instead of disconnected, assuming that no connection is desired.

I hope this helps. Please let me know if the problem persists.

**Comment by dcconner** [comment]
Closed as seemed to be issue with setup and no followup
