### ISSUE TITLE
FlexBE Chrome app disconnected: "InvalidServiceException: Service /rosapi/get_param does not exist"

### ISSUE THREAD

**Issue by josephcoombe** [team-vigir/flexbe_behavior_engine#43]
Hi! First of all, FlexBE seems really cool. Being able to generate SMACH code from drag-and-drop states is awesome!

Unfortunately, I am unable to execute my behavior from the Chrome app. It seems to be disconnected. I'm running `ros-kinetic-desktop-full`.

![screenshot 2017-11-16 15 33 08](https://user-images.githubusercontent.com/12258096/32917020-7b1f4c18-cae3-11e7-9c0d-e697e2085a94.png)

----
Here are my original terminal commands:

`$ roslaunch flexbe_onboard behavior_onboard.launch`
![roslaunch](https://user-images.githubusercontent.com/12258096/32917180-fb8fde80-cae3-11e7-9b39-1828c2595ec3.png)
  
`$ rosrun rosbridge_server rosbridge_websocket`
![rosbridge](https://user-images.githubusercontent.com/12258096/32917254-36734370-cae4-11e7-9573-28d6ce5ed88b.png)

----
Revised terminal commands:

`$ roslaunch flexbe_onboard behavior_onboard.launch`

`$ rosrun rosapi rosapi_node`

`$ rosrun rosbridge_server rosbridge_websocket`
![rosbridge_success](https://user-images.githubusercontent.com/12258096/32917800-ea325d64-cae5-11e7-92a5-3fbe9e7dd29b.png)

Starting the rosapi_node in a separate terminal prevents the `[ERROR] [1510868269.935593]: [Client 0] [id: call_service:/rosapi/get_param:1] call_service InvalidServiceException: Service /rosapi/get_param does not exist`
however, the FlexBE Chrome app still says it's disconnected

----
Additional info:

I ran `$ sudo apt-get install ros-kinetic-rosbridge-server` to make sure that rosbridge-server was installed & updated.

`$ rostopic list`
![rostopic_list](https://user-images.githubusercontent.com/12258096/32917957-5a0dd50a-cae6-11e7-92e5-e09996b620b3.png)

`$ rostopic echo /flexbe/heartbeat`
![rostopic_echo_flexbe_heartbeat](https://user-images.githubusercontent.com/12258096/32917998-82da79e8-cae6-11e7-8b36-3fa3dd57a2c3.png)

**Comment by pschillinger** [comment]
Thank you for the helpful error report! The fact that the heartbeat messages are coming through, but the Chrome app stays in "disconnect" indeed suggests a rosbridge problem. I saw the rosapi/get_param-error appear before in a nondeterministic way, but usually, avoiding this error by starting rosapi separately made it work again.

Did you start the Chrome app directly (from Chrome) or did you run ``roslaunch flexbe_widget behavior_ocs.launch``? It should not cause the reported error, but in general this is required to run behaviors from the Chrome app.

In any case, could I ask you to switch to the new [flexbe_app](https://github.com/flexbe/flexbe_app) instead of using the Chrome version? There have been multiple problems with rosbridge in the past, unfortunately. The version does not use it anymore and besides this, Google ends support for Chrome apps next year, so expect the FlexBE Chrome app to become deprecated soon and the new flexbe_app will be on master.

**Comment by josephcoombe** [comment]
I started the Chrome app directly from `chrome://apps/`.

Makes sense. I'll switch over the to the new flebe_app!

**Comment by josephcoombe** [comment]
Got started with the new [flexbe_app](https://github.com/flexbe/flexbe_app). It connects to ROS without any warning messages!

If I run into anything odd, I'll open an issue in its [repo](https://github.com/flexbe/flexbe_app). Thank you!
