### ISSUE TITLE
Containers or behaviors contained in a concurrency state are not executed when entering the concurrency state again

### ISSUE THREAD

**Issue by dvanthienen** [team-vigir/flexbe_behavior_engine#7]
Containers or behaviors contained in a concurrency state are not executed when entering the concurrency state again. See attached example:
A concurrency state has two concurrent states, 1) a container, containing a ContainerLogger state and a Wait state, and
2) a NotContainerLogger state. After this concurrency state is finished, another logger logs a "end of iteration" message and reenters the concurrency state.

Both ContainerLogger and NotContainerLogger state will log a message when executed the first time (=desired behavior), however, the following iterations, the ContainerLogger is not executed anymore (=the bug).

[test_concurrency_sm.py.txt](https://github.com/team-vigir/flexbe_behavior_engine/files/244233/test_concurrency_sm.py.txt)

**Comment by pschillinger** [comment]
Fixed it, thanks for pointing that out!

Note that, in your example, the NotContainerLogger can preempt the container. In general, it is not guaranteed that the inner container will be executed at all since the LogState immediately returns an outcome. In order to wait for both the LogState and the container to finish, connect them to the same outcome.
